noroadsleft000/gnome-network-stats

- AppController.js
- AppSettingsModel.js
- metadata.json
- net/DeviceModel.js
- net/NetworkMonitor.js
* Download, Upload speed numbers were wrong.
* Total data usage was resetting every time. initialize initialReading when ever it is undefined.
> Merged some bug fixes to main

- AppController.js
- README.md
- metadata.json
- net/DeviceModel.js
- net/DeviceMonitor.js
- net/NetworkMonitor.js
- ui/PopupView.js
* Add device name to init logs
* Renew minute timer by returning true
* Remove app settings listener on destory
* updated readme.md for logs command
* export DeviceMonitor class and move instance to ownership with DeviceModel
* Uninstall timers on deinit
> Release bug fixes to main

- locale/nl.po
> Added Dutch translation

- AppController.js
- net/DeviceModel.js
- utils/DateTimeUtils.js
Data reset is now optional.
User can choose daily, weekly, bi-weekly, monthly reset schedule.
Some minor name changes.
> Added more flexibility to choose reset schedule.

- TODO.txt
> Updated TODO.txt list

- metadata.json
- prefs.js
- utils/GtkUtils.js
- Added support for gnome 40.
- Added GtkUtils.js for Gtk3, Gtk4 abstraction.
> Added support for gnome 40

- locale/POTFILES.in
- locale/en_US.po
- locale/network-stats.pot
- locale/update_lang_template.sh
Removed file line numbers from language po files.
> Some minor improvements

- .gitignore
- README.md
- TODO.txt
Added different ways to reload shell.
Added Gnome Javascript guide link.
Updated ToDo list
Added gitignore file
> Updated documentation

- ui/ExpandableDeviceMenuItem.js
Added new line to display last reset point and reset button.
> Minor UI improvement

- metadata.json
**New Features:**
- Added flexibility to choose Daily, Weekly, Monthly reset schedule.
- Some minor UI improvements.
**Bug Fixes:**
- Added support for Gnome 40 and Ubuntu 21.10
> Release version 10

- AppController.js
- locale/en_US.po
- locale/network-stats.pot
- net/DeviceModel.js
- prefs.js
- utils/GenUtils.js
Addressed review comments for PR #32
> Addressed review comments for PR #32

- TODO.md
Added new tasks.
Marked some old tasks as completed.
> Updated TODO list

- metadata.json
> Release version 11

- metadata.json
- ui/ExpandableDeviceMenuItem.js
Added support for gnome 42
Changed last reset at icon
> Release version 14

- App.js
- AppController.js
- AppSettingsModel.js
- metadata.json
- net/DeviceModel.js
- net/NetworkMonitor.js
- utils/Logger.js
Save the data consumed (download, upload) separately.
Do not depend on **initialReading**, it gets reset on each reboot.
Use the saved values to warm up after system is rebooted.
> Save download and upload data to pref storage.

- TODO.md
- metadata.json
> Release version 17

- metadata.json
Release version 20
- Added support for gnome version 44
- Added Swedish locale support
> Release version 20

- metadata.json
> Added support for gnome 45

- metadata.json
Reverts noroadsleft000/gnome-network-stats#56
Major code and api changes needed for supporting gnome 45
> Revert "Added support for gnome 45"

- metadata.json
> Added gnome 47, 48 support

- extension.ts
- prefs.ts
- src/AppController.ts
- src/AppSettingsModel.ts
- src/net/NetworkMonitor.ts
- src/ui/AppView.ts
- src/ui/MainPanel.ts
- src/ui/PopupView.ts
- src/utils/Broadcasters.ts
- src/utils/Constants.ts
Added code improvements and missing documentation
> Added code improvements
